package com.axiomalaska.sos.harvester

/**
 * The units for observation measurements 
 */
object Units {
  val NONE = ""
  val INCHES = "inches"
  val UMOL_PER_MOL = "umol/mol"
  val MILES_PER_HOUR = "mph"
  val PARTS_PER_TRILLION = "ppt"
  val MILLIMETERS = "mm"
  val SECONDS = "s"
  val HECTOPASCAL = "hPa"
  val MILLIMOLES_PER_METER_SQUARED = "mmole/m2"
  val CENTIMETERS = "cm"
  val SATURATION = "% saturation"
  val MILLI_BAR = "mbar"
  val PARTS_PER_MILLION = "ppm"
  val VOLTAGE = "V"
  val METERS = "m"
  val STD_UNITS = "std units"
  val NEPHELOMETRIC_TURBIDITY_UNITS = "NTU"
  val WATT_PER_METER_SQUARED = "W/m2"
  val FAHRENHEIT = "F"
  val A = "A (hourly average)"
  val DEGREES = "degrees"
  val INCHES_OF_MERCURY = "Inches of Mercury"
  val PERCENT = "%"
  val CUBIC_FOOT_PER_SECOUND = "feet3 s-1"
  val CUBIC_METER_PER_SECOUND = "m3 s-1"
  val KNOTS = "Knots"
  val MILLIMETER_PER_MERCURY = "mm/Hg"
  val FEET = "feet"
  val MICRO_MHOS_PER_CENTIMETERS = "uMHOS/cm"
  val CELSIUS = "C"
  val METER_PER_SECONDS = "m/s"
  val MILLIGRAMS_PER_LITER = "mg/l"
  val MICROGRAMS_PER_LITER = "µg/L"
  val PARTS_PER_100_MILILETER = "#/100ml"
  val MILLI_EQUIVILANTS_OF_SOLVENT_PER_LITER = "mEq/L"
  val PCU = "PCU"
}